### ISSUE TITLE
How to use SimpleMM?

### ISSUE THREAD

**Issue by ds-sampaio** [opensimply/Simply-Memory-Manager#2]
How to use SimplyMM?
I entered the path in project options, declared it in uses, but nothing happens.

**Comment by opensimply** [comment]
Hi!

What do you mean "nothing happens"? You've done everything you need. Your actions replace the native memory manager to Simply Memory Manager (SMM). Now you can code in the usual way.
 
If you are using the Delphi IDE, the SMM should not be used. The Delphi built-in memory manager has a perfect performance.

If you want to check the leaks by using the [HeapTrc](https://wiki.freepascal.org/heaptrc) in your project, the SimplySMM unit must be excluded the  from the "uses" statement.

uses
  // SimplyMM,
  .... 

[The SMM homepage](https://opensimply.org/smm/)
Download the latest SMM version from 5 Mar 2022.

**Comment by ds-sampaio** [comment]
When I say that "nothing happens" it is that I had not understood what the
purpose of the SMM library is. If I understand correctly, does it work to
free up memory allocation caused by windows? Can I use SMM for lazarus
linux?

Em sáb., 5 de mar. de 2022 às 16:56, Free simulation software <
***@***.***> escreveu:

**Comment by opensimply** [comment]
Hi,
The SMM allocates, reallocates and frees memory on Windows. The SMM is a replacement for the native memory manager for Free Pascal and Lazarus projects on Windows only, since the native Free Pascal memory manager uses certain Windows functions for memory allocation and freeing, which cause fatal errors when large amount of memory is reusing multiply. The SMM prevents such errors. 

The SMM can be used in the single-thread mode on Linux, but it is not required. The native Free Pascal memory manager runs on Linux as well with no issues (as far as I noticed).

**Comment by ds-sampaio** [comment]
Now I can understand, thank you for the explanation and for your time.

Em sáb., 5 de mar. de 2022 às 18:23, Free simulation software <
***@***.***> escreveu:
